#
#. This config file adds support for Netlify CMS, exposed at /admin on the running site.
# In order to use this on your site,
#. 1) replace instances of "exampleSite/......" with the appropriate paths, relative from repository root.
#. 2) replace repo path in `backend` settings, and set branch to master.
#  3) Optionally enable the [editor workflow](https://www.netlifycms.org/docs/configuration-options/#publish-mode) which uses PRs for content changes
#  4) Optionally enable [open authoring](https://www.netlifycms.org/docs/open-authoring/) for community sites, which requires #3
#  
#

backend:
  name: github
  repo: alongwy/website
  branch: docs
  cms_label_prefix: netlify-cms/
  site_domain: doc-alongwy.netlify.app

locale: 'zh_Hans'
media_folder: "src/media" # Folder where user uploaded files should go
public_folder: "/media"

collections: # A list of collections the CMS should be able to edit
  - name: "docs" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "文档" # Used in the UI, ie.: "New Post"
    folder: "src" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    media_folder: '{{filename}}'
    public_folder: '{{filename}}'
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string" }
      - {label: "正文", name: "body", widget: "markdown"}
       
  - name: 'settings'
    label: '设置'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'general'
        label: '网站设置'
        file: 'book.toml'
        extension: toml
        description: '通用网站设置'
        fields:
          - name: 'book'
            label: '参数'
            widget: 'object'
            fields: 
              - { label: '作者', name: 'authors', widget: 'list' }
              - { label: '语言', name: 'language', widget: 'string', default: "cn" }
              - { label: '多语', name: 'multilingual', widget: 'boolean', default:false }

          